import type { Artwork } from "./types";

export const SEED_ARTWORKS: Artwork[] = [
  {
    id: "girl-with-pearl-earring",
    title: "Girl with a Pearl Earring",
    artistName: "Johannes Vermeer",
    artistId: "seed-vermeer",
    medium: "Oil on canvas",
    year: 1665,
    dimensions: "44.5 × 39 cm",
    museum: "Mauritshuis",
    location: "The Hague",
    categories: ["Baroque", "Portraits"],
    imageUrl: "",
    has3D: true,
    description:
      "Often called the 'Mona Lisa of the North'. A single pearl catches the light — the sitter's identity remains art history's greatest mystery.",
    likes: 0,
    likedBy: [],
    savedBy: [],
    createdAt: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "judith-beheading-holofernes",
    title: "Judith Beheading Holofernes",
    artistName: "Caravaggio",
    artistId: "seed-caravaggio",
    medium: "Oil on canvas",
    year: 1602,
    dimensions: "145 × 195 cm",
    museum: "Galleria Nazionale d'Arte Antica",
    location: "Rome",
    categories: ["Italian Baroque"],
    imageUrl: "",
    has3D: false,
    description:
      "Caravaggio's dramatic chiaroscuro turns a biblical scene into a visceral, almost uncomfortable confrontation.",
    likes: 0,
    likedBy: [],
    savedBy: [],
    createdAt: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "mona-lisa",
    title: "Mona Lisa",
    artistName: "Leonardo da Vinci",
    artistId: "seed-davinci",
    medium: "Oil on panel",
    year: 1503,
    dimensions: "77 × 53 cm",
    museum: "Louvre Museum",
    location: "Paris",
    categories: ["Renaissance", "Portraits"],
    imageUrl: "",
    has3D: true,
    description:
      "The world's most recognised painting. Leonardo's sfumato technique gives the face an unrivalled softness.",
    likes: 0,
    likedBy: [],
    savedBy: [],
    createdAt: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "starry-night",
    title: "The Starry Night",
    artistName: "Vincent van Gogh",
    artistId: "seed-vangogh",
    medium: "Oil on canvas",
    year: 1889,
    dimensions: "73.7 × 92.1 cm",
    museum: "Museum of Modern Art",
    location: "New York",
    categories: ["Post-Impressionism"],
    imageUrl: "",
    has3D: false,
    description:
      "Swirling night sky painted from the window of Van Gogh's asylum room. Energy barely contained by the canvas.",
    likes: 0,
    likedBy: [],
    savedBy: [],
    createdAt: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "birth-of-venus",
    title: "The Birth of Venus",
    artistName: "Sandro Botticelli",
    artistId: "seed-botticelli",
    medium: "Tempera on canvas",
    year: 1484,
    dimensions: "172.5 × 278.9 cm",
    museum: "Uffizi Gallery",
    location: "Florence",
    categories: ["Renaissance"],
    imageUrl: "",
    has3D: false,
    description:
      "The goddess of love emerges from the sea on a shell. A defining image of the Italian Renaissance.",
    likes: 0,
    likedBy: [],
    savedBy: [],
    createdAt: "2024-01-01T00:00:00.000Z",
  },
];
