import type { Artwork } from "./types";

export const SEED_ARTWORKS: Artwork[] = [
  {
    id: "girl-with-pearl-earring",
    title: "Girl with a Pearl Earring",
    artistName: "Johannes Vermeer",
    artistId: "seed-vermeer",
    medium: "Oil on canvas",
    year: 1665,
    dimensions: "44.5 × 39 cm",
    museum: "Mauritshuis",
    location: "The Hague",
    categories: ["Baroque", "Portraits"],
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/1665_Girl_with_a_Pearl_Earring.jpg/800px-1665_Girl_with_a_Pearl_Earring.jpg",
    has3D: false,
    description:
      "Often called the 'Mona Lisa of the North'. A single pearl catches the light — the sitter's identity remains art history's greatest mystery.",
    likes: 241,
    dislikes: 0,
    likedBy: [],
    dislikedBy: [],
    savedBy: [],
    createdAt: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "judith-beheading-holofernes",
    title: "Judith Beheading Holofernes",
    artistName: "Caravaggio",
    artistId: "seed-caravaggio",
    medium: "Oil on canvas",
    year: 1602,
    dimensions: "145 × 195 cm",
    museum: "Galleria Nazionale d'Arte Antica",
    location: "Rome",
    categories: ["Italian Baroque"],
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Caravaggio_Judith_Beheading_Holofernes.jpg/800px-Caravaggio_Judith_Beheading_Holofernes.jpg",
    has3D: false,
    description:
      "Caravaggio's dramatic chiaroscuro turns a biblical scene into a visceral, almost uncomfortable confrontation.",
    likes: 187,
    dislikes: 0,
    likedBy: [],
    dislikedBy: [],
    savedBy: [],
    createdAt: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "mona-lisa",
    title: "Mona Lisa",
    artistName: "Leonardo da Vinci",
    artistId: "seed-davinci",
    medium: "Oil on panel",
    year: 1503,
    dimensions: "77 × 53 cm",
    museum: "Louvre Museum",
    location: "Paris",
    categories: ["Renaissance", "Portraits"],
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/800px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg",
    has3D: true,
    arWebId: "mona-lisa",
    description:
      "The world's most recognised painting. Leonardo's sfumato technique gives the face an unrivalled softness.",
    likes: 1842,
    dislikes: 0,
    likedBy: [],
    dislikedBy: [],
    savedBy: [],
    createdAt: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "starry-night",
    title: "The Starry Night",
    artistName: "Vincent van Gogh",
    artistId: "seed-vangogh",
    medium: "Oil on canvas",
    year: 1889,
    dimensions: "73.7 × 92.1 cm",
    museum: "Museum of Modern Art",
    location: "New York",
    categories: ["Post-Impressionism"],
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/1280px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg",
    has3D: true,
    arWebId: "starry-night",
    description:
      "Swirling night sky painted from the window of Van Gogh's asylum room. Energy barely contained by the canvas.",
    likes: 976,
    dislikes: 0,
    likedBy: [],
    dislikedBy: [],
    savedBy: [],
    createdAt: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "the-scream",
    title: "The Scream",
    artistName: "Edvard Munch",
    artistId: "seed-munch",
    medium: "Oil, tempera and pastel on cardboard",
    year: 1893,
    dimensions: "91 × 73 cm",
    museum: "National Gallery of Norway",
    location: "Oslo",
    categories: ["Expressionism"],
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg/800px-Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg",
    has3D: true,
    arWebId: "the-scream",
    description:
      "The anguished face has become one of the most recognisable in art history — a symbol of modern anxiety.",
    likes: 634,
    dislikes: 0,
    likedBy: [],
    dislikedBy: [],
    savedBy: [],
    createdAt: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "birth-of-venus",
    title: "The Birth of Venus",
    artistName: "Sandro Botticelli",
    artistId: "seed-botticelli",
    medium: "Tempera on canvas",
    year: 1484,
    dimensions: "172.5 × 278.9 cm",
    museum: "Uffizi Gallery",
    location: "Florence",
    categories: ["Renaissance"],
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg/1280px-Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg",
    has3D: false,
    description:
      "The goddess of love emerges from the sea on a shell. A defining image of the Italian Renaissance.",
    likes: 512,
    dislikes: 0,
    likedBy: [],
    dislikedBy: [],
    savedBy: [],
    createdAt: "2024-01-01T00:00:00.000Z",
  },
];
