import type { Artwork } from "./types";

export const SEED_ARTWORKS: Artwork[] = [
  // ── Renaissance ──────────────────────────────────────────
  {
    id: "girl-with-pearl-earring",
    title: "Girl with a Pearl Earring",
    artistName: "Johannes Vermeer",
    artistId: "seed-vermeer",
    medium: "Oil on canvas",
    year: 1665,
    dimensions: "44.5 × 39 cm",
    museum: "Mauritshuis",
    location: "The Hague",
    categories: ["Renaissance"],
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/1665_Girl_with_a_Pearl_Earring.jpg/1280px-1665_Girl_with_a_Pearl_Earring.jpg",
    has3D: false,
    description:
      "Often called the 'Mona Lisa of the North'. A single pearl catches the light — the sitter's identity remains art history's greatest mystery.",
    likes: 241,
    likedBy: [],
    savedBy: [],
    createdAt: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "judith-beheading-holofernes",
    title: "Judith Beheading Holofernes",
    artistName: "Caravaggio",
    artistId: "seed-caravaggio",
    medium: "Oil on canvas",
    year: 1602,
    dimensions: "145 × 195 cm",
    museum: "Galleria Nazionale d'Arte Antica",
    location: "Rome",
    categories: ["Renaissance"],
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Caravaggio_Judith_Beheading_Holofernes.jpg/1280px-Caravaggio_Judith_Beheading_Holofernes.jpg",
    has3D: false,
    description:
      "Caravaggio's dramatic chiaroscuro turns a biblical scene into a visceral, almost uncomfortable confrontation.",
    likes: 187,
    likedBy: [],
    savedBy: [],
    createdAt: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "mona-lisa",
    title: "Mona Lisa",
    artistName: "Leonardo da Vinci",
    artistId: "seed-davinci",
    medium: "Oil on panel",
    year: 1503,
    dimensions: "77 × 53 cm",
    museum: "Louvre Museum",
    location: "Paris",
    categories: ["Renaissance"],
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/1280px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg",
    has3D: true,
    arWebId: "mona-lisa",
    description:
      "The world's most recognised painting. Leonardo's sfumato technique gives the face an unrivalled softness.",
    likes: 1842,
    likedBy: [],
    savedBy: [],
    createdAt: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "birth-of-venus",
    title: "The Birth of Venus",
    artistName: "Sandro Botticelli",
    artistId: "seed-botticelli",
    medium: "Tempera on canvas",
    year: 1484,
    dimensions: "172.5 × 278.9 cm",
    museum: "Uffizi Gallery",
    location: "Florence",
    categories: ["Renaissance"],
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg/1280px-Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg",
    has3D: false,
    description:
      "The goddess of love emerges from the sea on a shell. A defining image of the Italian Renaissance.",
    likes: 512,
    likedBy: [],
    savedBy: [],
    createdAt: "2024-01-01T00:00:00.000Z",
  },

  // ── Moderne ───────────────────────────────────────────────
  {
    id: "starry-night",
    title: "The Starry Night",
    artistName: "Vincent van Gogh",
    artistId: "seed-vangogh",
    medium: "Oil on canvas",
    year: 1889,
    dimensions: "73.7 × 92.1 cm",
    museum: "Museum of Modern Art",
    location: "New York",
    categories: ["Moderne"],
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/1280px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg",
    has3D: true,
    arWebId: "starry-night",
    description:
      "Swirling night sky painted from the window of Van Gogh's asylum room. Energy barely contained by the canvas.",
    likes: 976,
    likedBy: [],
    savedBy: [],
    createdAt: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "the-scream",
    title: "The Scream",
    artistName: "Edvard Munch",
    artistId: "seed-munch",
    medium: "Oil, tempera and pastel on cardboard",
    year: 1893,
    dimensions: "91 × 73 cm",
    museum: "National Gallery of Norway",
    location: "Oslo",
    categories: ["Moderne"],
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg/1280px-Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg",
    has3D: true,
    arWebId: "the-scream",
    description:
      "The anguished face has become one of the most recognisable in art history — a symbol of modern anxiety.",
    likes: 634,
    likedBy: [],
    savedBy: [],
    createdAt: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "vangogh-yellow-house",
    title: "The Yellow House",
    artistName: "Vincent van Gogh",
    artistId: "seed-vangogh",
    medium: "Oil on canvas",
    year: 1888,
    dimensions: "72 × 91.5 cm",
    museum: "Van Gogh Museum",
    location: "Amsterdam",
    categories: ["Moderne"],
    imageUrl: "/images/Van-Gogh-The-Yellow-House-1888-Arles-1024-x-695.webp",
    has3D: false,
    description:
      "The house Van Gogh rented in Arles, where he dreamed of founding an artists' colony. The fierce Provençal sunlight is captured in pure chrome yellow.",
    likes: 389,
    likedBy: [],
    savedBy: [],
    createdAt: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "vangogh-self-portrait-1889",
    title: "Self-Portrait",
    artistName: "Vincent van Gogh",
    artistId: "seed-vangogh",
    medium: "Oil on canvas",
    year: 1889,
    dimensions: "65 × 54 cm",
    museum: "Musée d'Orsay",
    location: "Paris",
    categories: ["Moderne"],
    imageUrl: "/images/Vincent-Van-Gogh-Self-portrait-1889-St-Remy-de-Provence-scaled.webp",
    has3D: false,
    description:
      "Painted at Saint-Rémy asylum, one of his last self-portraits. The swirling brushwork of the background contrasts with his composed, almost defiant gaze.",
    likes: 714,
    likedBy: [],
    savedBy: [],
    createdAt: "2024-01-01T00:00:00.000Z",
  },

  // ── Abstrait ──────────────────────────────────────────────
  {
    id: "kandinsky-composition-viii",
    title: "Composition VIII",
    artistName: "Wassily Kandinsky",
    artistId: "seed-kandinsky",
    medium: "Oil on canvas",
    year: 1923,
    dimensions: "140 × 201 cm",
    museum: "Guggenheim Museum",
    location: "New York",
    categories: ["Abstrait"],
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Vassily_Kandinsky%2C_1923_-_Composition_8%2C_huile_sur_toile%2C_140_cm_x_201_cm%2C_Mus%C3%A9e_Guggenheim%2C_New_York.jpg/1280px-Vassily_Kandinsky%2C_1923_-_Composition_8%2C_huile_sur_toile%2C_140_cm_x_201_cm%2C_Mus%C3%A9e_Guggenheim%2C_New_York.jpg",
    has3D: false,
    description:
      "A symphony of geometric forms — circles, triangles, lines — that Kandinsky believed could evoke pure emotion without depicting any object.",
    likes: 423,
    likedBy: [],
    savedBy: [],
    createdAt: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "mondrian-composition-ii",
    title: "Composition II in Red, Blue and Yellow",
    artistName: "Piet Mondrian",
    artistId: "seed-mondrian",
    medium: "Oil on canvas",
    year: 1930,
    dimensions: "46 × 46 cm",
    museum: "Kunsthaus Zürich",
    location: "Zürich",
    categories: ["Abstrait"],
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Piet_Mondriaan%2C_1930_-_Mondrian_Composition_II_in_Red%2C_Blue%2C_and_Yellow.jpg/800px-Piet_Mondriaan%2C_1930_-_Mondrian_Composition_II_in_Red%2C_Blue%2C_and_Yellow.jpg",
    has3D: false,
    description:
      "Primary colours separated by black lines. Mondrian's neoplasticism reduces reality to its most essential visual elements.",
    likes: 318,
    likedBy: [],
    savedBy: [],
    createdAt: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "malevich-black-square",
    title: "Black Square",
    artistName: "Kazimir Malevich",
    artistId: "seed-malevich",
    medium: "Oil on linen",
    year: 1915,
    dimensions: "79.5 × 79.5 cm",
    museum: "Tretyakov Gallery",
    location: "Moscow",
    categories: ["Abstrait"],
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Malevich_black_square.jpg/1280px-Malevich_black_square.jpg",
    has3D: false,
    description:
      "A black square on a white field — one of the most radical acts in art history. Malevich called it 'the zero of form', the beginning of pure abstraction.",
    likes: 501,
    likedBy: [],
    savedBy: [],
    createdAt: "2024-01-01T00:00:00.000Z",
  },

  // ── Surréalisme ───────────────────────────────────────────
  {
    id: "dali-persistence-of-memory",
    title: "The Persistence of Memory",
    artistName: "Salvador Dalí",
    artistId: "seed-dali",
    medium: "Oil on canvas",
    year: 1931,
    dimensions: "24 × 33 cm",
    museum: "Museum of Modern Art",
    location: "New York",
    categories: ["Surréalisme"],
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/en/d/dd/The_Persistence_of_Memory.jpg",
    has3D: false,
    description:
      "Melting clocks draped over a dreamscape. Dalí's most iconic image questions the rigidity of time itself.",
    likes: 1204,
    likedBy: [],
    savedBy: [],
    createdAt: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "magritte-son-of-man",
    title: "The Son of Man",
    artistName: "René Magritte",
    artistId: "seed-magritte",
    medium: "Oil on canvas",
    year: 1964,
    dimensions: "116 × 89 cm",
    museum: "Private collection",
    location: "Belgium",
    categories: ["Surréalisme"],
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/en/e/e9/Magritte_TheSonOfMan.jpg",
    has3D: false,
    description:
      "A bowler-hatted man with a green apple obscuring his face. Magritte plays with visibility, identity and the hidden nature of things.",
    likes: 876,
    likedBy: [],
    savedBy: [],
    createdAt: "2024-01-01T00:00:00.000Z",
  },
];
